# Basic site configuration
title: ER Designer
description: Professional Entity Relationship Diagram (ERD) Tool for Database Design | macOS
# Keep the baseurl empty if the repository name is username.github.io
# Otherwise use the repository name
baseurl: "/er-designer-support"
url: ""

# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# GitHub Pages specific settings
github:
  is_project_page: true
  repository_url: https://github.com/chainray01/er-designer-support
  owner_url: https://github.com/chainray01